In [2]:
### IMPORTING LIBRARIES

from bs4 import BeautifulSoup
import requests
import json
import os
import re
import time
import pandas as pd
from pprint import pprint

In [3]:
### API KEY

apikey = ("nmXlGGCBJPt0gLK9qPIrG9eVge6aFjgn")
apikey
# Article Search:
# https://api.nytimes.com/svc/search/v2/articlesearch.json?q=<QUERY>&api-key=<APIKEY>

'nmXlGGCBJPt0gLK9qPIrG9eVge6aFjgn'

In [4]:
### GETTING THE DATA FROM API AND READING IT USING JSON

query = "Mexico"
begin_date = "20160101"  # YYYYMMDD
#filter_query = ""  # http://www.lucenetutorial.com/lucene-query-syntax.html
page = "1"  # <0-100>
sort = "newest"  # newest, oldest
query_url = f"https://api.nytimes.com/svc/search/v2/articlesearch.json?" \
            f"q={query}" \
            f"&api-key={apikey}" \
            f"&begin_date={begin_date}" \
            f"&page={page}" \
            f"&sort={sort}"

r = requests.get(query_url)
r = r.json()

In [24]:
### RUNNING THE DIFFERENT PAGES OF THE WEBSITE AND EXTRACT INFORMATION


pd.set_option('display.colheader_justify', 'center')

#re-arrange the 'Data_columns' vector below to re-arrange the columns in the final table.
Data_columns = ('Title', 'Date', 'Abstract', 'Author', 'Keyword 1', 'Keyword 2')
result = pd.DataFrame(columns = Data_columns)

#The range below goes only from 1 to 7 pages (Python reads that as 1 to 10 and not 1 to 100). 
#Any higher range will throw errors because I have restricted the date to 01/01/2016.

for i in range(1,7):
    query = "Mexico"
    begin_date = "20160101"  # YYYYMMDD
    filter_query = "\"body:(\"Mexico\")AND title:(\"MEXICO\")\""  # http://www.lucenetutorial.com/lucene-query-syntax.html
    page = i  # <0-100>
    sort = "newest"  # newest, oldest
    query_url = f"https://api.nytimes.com/svc/search/v2/articlesearch.json?" \
                f"q={query}" \
                f"&api-key={apikey}" \
                f"&begin_date={begin_date}" \
                f"&page={page}" \
                f"&sort={sort}"

    r = requests.get(query_url)
    r = r.json()

  

    for i in range(1,7):
        date = r['response']['docs'][i]['pub_date']
        result = result.append({
            'Title': r['response']['docs'][i]['headline']['main'],
            'Date' : date[0:10],
            #'Keyword 1' : r['response']['docs'][i]['keywords'][0]['value'],
            #'Keyword 2' : r['response']['docs'][i]['keywords'][1]['value'],
            #'keywords 3' : r['response']['docs'][i]['keywords'][2]['value'],
            #'keywords 4' : r['response']['docs'][i]['keywords'][3]['value'],
            #'keywords 5' : r['response']['docs'][i]['keywords'][4]['value'],
            'Abstract' : r['response']['docs'][i]['abstract'],
            'Author' : r['response']['docs'][i]['byline']['original']
        }, ignore_index = True, sort = False)
        
result = result.style.set_table_styles([dict(selector='th', props=[('text-align', 'center')])])
#result.set_properties(**{'text-align': 'center'}).hide_index()     

result